[env:front]
platform           = espressif32
board              = esp32dev
framework          = arduino
monitor_speed      = 115200
upload_speed       = 921600

lib_deps =
    h2zero/NimBLE-Arduino @ ^1.4.2
    fastled/FastLED       @ ^3.7.0
    bblanchon/ArduinoJson @ ^6.21.0

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_BT_NIMBLE_ENABLED=1

extra_scripts = ../merge_firmware.py
